/** Declaration file generated by dts-gen */

export function activateSender(senderEmail: any, code: any): Promise<any>;

export function addEmails(id: any, emails: any): Promise<any>;

export function addSender(senderName: any, senderEmail: any): Promise<any>;

export function addToBlackList(emails: any, comment: any): Promise<any>;

export function campaignCost(id: any): Promise<any>;

export function campaignStatByCountries(id: any): Promise<any>;

export function campaignStatByReferrals(id: any): Promise<any>;

export function cancelCampaign(id: any): Promise<any>;

export function createAddressBook(bookName: any): Promise<any>;

export function createCampaign(senderName: any, senderEmail: any, subject: any, body: any, bookId: any, name: any, attachments: any): Promise<any>;

export function editAddressBook(id: any, bookName: any): Promise<any>;

export function emailStatByCampaigns(email: any): Promise<any>;

export function getBalance(currency: any): Promise<void>;

export function getBlackList(): Promise<void>;

export function getBookInfo(id: any): Promise<any>;

export function getCampaignInfo(id: any): Promise<any>;

export function getEmailGlobalInfo(email: any): Promise<any>;

export function getEmailInfo(id: any, email: any): Promise<any>;

export function getEmailTemplate(id: any): Promise<any>;

export function getEmailsFromBook(id: any): Promise<any>;

export function getSenderActivationMail(senderEmail: any): Promise<any>;

export function getToken(): Promise<void>;

export function init(client_id: string, secret: string): Promise<void>;

export function listAddressBooks(limit: any, offset: any): Promise<void>;

export function listCampaigns(limit: any, offset: any): Promise<void>;

export function listEmailTemplates(): Promise<void>;

export function listSenders(): Promise<void>;

export function removeAddressBook(id: any): Promise<any>;

export function removeEmailFromAllBooks(email: any): Promise<any>;

export function removeEmails(id: any, emails: any): Promise<any>;

export function removeFromBlackList(emails: any): Promise<any>;

export function removeSender(senderEmail: any): Promise<any>;

export function smsAddCampaign(sender_name: any, addressbook_id: any, body: any, date: any, transliterate: any): Promise<any>;

export function smsAddPhones(addressbook_id: any, phones: any): Promise<any>;

export function smsAddPhonesToBlacklist(phones: any, comment: any): Promise<any>;

export function smsAddPhonesWithVariables(addressbook_id: any, phones: any): Promise<any>;

export function smsCancelCampaign(campaign_id: any): Promise<any>;

export function smsDeleteCampaign(campaign_id: any): Promise<any>;

export function smsDeletePhonesFromBlacklist(phones: any): Promise<any>;

export function smsGetBlackList(): Promise<void>;

export function smsGetCampaignCost(sender_name: any, body: any, addressbook_id: any, phones: any): Promise<any>;

export function smsGetCampaignInfo(campaign_id: any): Promise<any>;

export function smsGetListCampaigns(date_from: any, date_to: any): Promise<void>;

export function smsGetPhoneInfo(addressbook_id: any, phone: any): Promise<any>;

export function smsGetPhonesInfoFromBlacklist(phones: any): Promise<any>;

export function smsRemovePhones(addressbook_id: any, phones: any): Promise<any>;

export function smsSend(sender_name: any, phones: any, body: any, date: any, transliterate: any, route: any): Promise<any>;

export function smsUpdatePhonesVariables(addressbook_id: any, phones: any, variables: any): Promise<any>;

export function smtpAddDomain(email: any): Promise<any>;

export function smtpGetEmailInfoById(id: any): Promise<any>;

export function smtpListAllowedDomains(): Promise<void>;

export function smtpListEmails(limit: any, offset: any, fromDate: any, toDate: any, sender: any, recipient: any): Promise<void>;

export function smtpListIP(): Promise<void>;

export function smtpRemoveFromUnsubscribe(emails: any): Promise<any>;

export function smtpSendMail(email: any): Promise<any>;

export function smtpUnsubscribeEmails(emails: any): Promise<any>;

export function smtpVerifyDomain(email: any): Promise<any>;

export function updateEmailVariables(id: any, email: any, variables: any): Promise<any>;

